"""Atomic JSON storage for offline diagnostic sessions.

JSON keeps the evidence inspectable and portable. Writes use a sibling
temporary file followed by replace so a power loss cannot leave a
half-written session in place.
"""

from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path

from notescan.domain.models import DiagnosticSession


class StorageError(RuntimeError):
    """Raised when a session cannot be loaded or saved safely."""


class SessionStore:
    """Persist sessions below a dedicated application directory."""

    def __init__(self, root: str | os.PathLike[str]) -> None:
        self.root = Path(root)
        self.root.mkdir(parents=True, exist_ok=True)

    def _path_for(self, session_id: str) -> Path:
        # IDs are generated by the app, but reject path separators for imports.
        if not session_id or Path(session_id).name != session_id or session_id in {".", ".."}:
            raise StorageError("Invalid session id")
        return self.root / f"{session_id}.json"

    def save(self, session: DiagnosticSession) -> Path:
        path = self._path_for(session.session_id)
        payload = json.dumps(session.to_dict(), indent=2, ensure_ascii=False, sort_keys=True)
        fd, temporary = tempfile.mkstemp(
            prefix=f".{session.session_id}.", suffix=".tmp", dir=self.root
        )
        try:
            with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
                handle.write(payload)
                handle.write("\n")
                handle.flush()
                os.fsync(handle.fileno())
            Path(temporary).replace(path)
        except (OSError, TypeError) as exc:
            try:
                Path(temporary).unlink(missing_ok=True)
            except OSError:
                pass
            raise StorageError(f"Could not save session {session.session_id}: {exc}") from exc
        return path

    def load(self, session_id: str) -> DiagnosticSession:
        path = self._path_for(session_id)
        try:
            with path.open("r", encoding="utf-8") as handle:
                data = json.load(handle)
            return DiagnosticSession.from_dict(data)
        except FileNotFoundError as exc:
            raise StorageError(f"Session not found: {session_id}") from exc
        except (OSError, ValueError, TypeError, KeyError) as exc:
            raise StorageError(f"Could not load session {session_id}: {exc}") from exc

    def list_sessions(self) -> list[DiagnosticSession]:
        sessions: list[DiagnosticSession] = []
        for path in sorted(self.root.glob("*.json")):
            try:
                with path.open("r", encoding="utf-8") as handle:
                    sessions.append(DiagnosticSession.from_dict(json.load(handle)))
            except (OSError, ValueError, TypeError, KeyError) as exc:
                raise StorageError(f"Could not load session file {path.name}: {exc}") from exc
        return sorted(sessions, key=lambda item: item.started_at, reverse=True)

    def export_json(self, session_id: str, destination: str | os.PathLike[str]) -> Path:
        session = self.load(session_id)
        target = Path(destination)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(
            json.dumps(session.to_dict(), indent=2, ensure_ascii=False, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        return target

    def import_json(self, source: str | os.PathLike[str]) -> Path:
        source_path = Path(source)
        try:
            with source_path.open("r", encoding="utf-8") as handle:
                session = DiagnosticSession.from_dict(json.load(handle))
        except (OSError, ValueError, TypeError, KeyError) as exc:
            raise StorageError(f"Could not import session {source_path}: {exc}") from exc
        return self.save(session)
